In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

data = datasets.load_iris()
X = data.data
y = data.target

In [ ]:
class My_Pca:
  def __init__(self, n_components):
    self.n_components = n_components
    self.components = None
    self.eig_values = None
    self.mean = None
    self.std = None

  def fit(self, X):
    self.mean = np.mean(X, axis = 0)
    self.std = np.std(X, axis = 0)

    X = (X - self.mean) / self.std

    cov = np.cov(X.T)

    eigval, eigvec = np.linalg.eig(cov)

    idx = np.argsort(eigval)[::-1]
    eigval = eigval[idx]
    eigvec = eigvec[idx]

    self.components = eigvec[:self.n_components]
    self.eig_values = eigval[:self.n_components]

  def transform(self, X):
    X = (X - self.mean) / self.std
    return np.dot(X, self.components.T)
  
  def get_components(self):
    return self.components

  def get_explained_variance(self):
    return self.eig_values


  def get_explained_variance_ratio(self):
    explained_variance_ratio = np.divide(self.eig_values, np.sum(self.eig_values))
    return explained_variance_ratio[:self.n_components]

In [ ]:
pca = PCA(n_components=2)

pca.fit(X)

principal_comps_builtin = pca.components_.T

for i,component in enumerate(pca.components_):
    print(f'principal component {i}')
    print(component)
    print()


principal component 0
[ 0.52106591 -0.26934744  0.5804131   0.56485654]

principal component 1
[0.37741762 0.92329566 0.02449161 0.06694199]



In [ ]:
pca.explained_variance_ratio_

array([0.72962445, 0.22850762])

In [ ]:
pca.explained_variance_

array([2.93808505, 0.9201649 ])

In [ ]:
pca.components_

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199]])

In [ ]:
my_pca = My_Pca(2)

In [ ]:
my_pca.fit(X)

In [ ]:
my_pca.explained_variance_()

array([2.93808505, 0.9201649 ])

In [ ]:
my_pca.explained_variance_ratio_()

array([0.76150718, 0.23849282])

In [ ]:
my_pca.components_()

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962]])